# -----------------------------------------------------------------------------
# jtag_ctrl.tcl
#
# Replaces the OpenCL host for the Vivado flow: configures kernels and reads
# counters over the JTAG-to-AXI Master instead of XRT.
#
# ASCII ONLY. Vivado's Tcl console mangles non-ASCII output (the console
# encoding is not UTF-8 on Windows), which turns every message into garbage
# and makes error text unreadable. Keep all comments and puts strings ASCII.
#
# Mapping to the Vitis version (host/hls_ouch_krnl/host.cpp):
#     setArg(i, v)      -> write to s_axi_control at the argument offset
#     enqueueTask(k)    -> write ap_start=1 (ap_ctrl_hs kernels only!)
#     reading counters  -> read s_axi_control (OpenCL could not do this at all)
#
# Run in Hardware Manager after programming the device:
#     open_hw_manager; connect_hw_server; open_hw_target
#     current_hw_device [lindex [get_hw_devices] 0]
#     source scripts/vivado/jtag_ctrl.tcl
#
#     hls_ouch_krnl (has s_axi_control -- listenPort/enable/counters):
#         ouch_bringup 7001 "0a01d498" "000a35029de5"
#         NUM_QSFP=2: ouch_bringup_dual 7001 "0a01d498" "000a35029de5" \
#                                       7002 "0a01d499" "000a35029de6"
#
#     hls_echo_krnl (port hardcoded, NO s_axi_control -- network only):
#         echo_bringup "0a01d498" "000a35029de5"
#         NUM_QSFP=2: echo_bringup_dual "0a01d498" "000a35029de5" \
#                                        "0a01d499" "000a35029de6"
#
#     hls_echo_probe_dual_krnl (TCP stack latency measurement):
#         see the epd_* section at the bottom of this file
#
#     Every procedure below can also be called on its own via the trailing
#     argument n (1=QSFP0, 2=QSFP1).
#
# -----------------------------------------------------------------------------
# IMPORTANT -- two different control protocols:
#
#   network_krnl is declared ap_ctrl_hs (see kernel/network_krnl/
#   network_krnl.xml, hwControlProtocol="ap_ctrl_hs"). It NEEDS ap_start,
#   otherwise the stack never starts and everything silently stalls. In Vitis
#   this was done by enqueueTask().
#
#   hls_ouch_krnl is declared ap_ctrl_none (#pragma HLS INTERFACE ap_ctrl_none
#   port=return). It has no ap_start register at all -- the kernel "flows" as
#   long as the clock is running. That is why its enable argument acts as the
#   permission to start: see the comment at ouch_listen in hls_ouch_krnl.cpp
#   about the race.
# -----------------------------------------------------------------------------

# s_axi_control base addresses. build_bd.tcl sets them explicitly
# (_addr_network/_addr_user, step 0x20000 between channels) and checks the
# result, so this is just the same formula. Channel N=1 is QSFP0, N=2 is
# QSFP1, and so on. If you change this, change it in both files.
proc ouch_base_network {{n 1}} { return [expr {($n - 1) * 0x20000}] }
proc ouch_base_user    {{n 1}} { return [expr {($n - 1) * 0x20000 + 0x10000}] }

# Kept for backwards compatibility with older single-channel (N=1) calls --
# new code should use ouch_base_network N / ouch_base_user N.
set ::OUCH_BASE_NETWORK [ouch_base_network 1]
set ::OUCH_BASE_USER    [ouch_base_user 1]

# network_krnl register offsets -- taken from network_krnl.xml (the offset
# attribute of each <arg>), not guessed.
set ::NET_OFF_AP_CTRL   0x000
set ::NET_OFF_IP_ADDR   0x010
set ::NET_OFF_MAC_ADDR  0x018
set ::NET_OFF_ARP       0x024
set ::NET_OFF_AXI00_PTR 0x02c
set ::NET_OFF_AXI01_PTR 0x038

# hls_ouch_krnl register offsets.
#
# Taken from xhls_ouch_krnl_hw.h generated by export_design
# (ouch_ip_proj/sol1/impl/ip/drivers/hls_ouch_krnl_v1_0/src/) -- not guessed.
# export_hls_ip.tcl prints them at the end of its run; re-check them whenever
# the kernel signature changes.
#
# The C++ argument order does NOT determine the offsets: HLS inserts ap_vld
# registers for output values (0x20 for rxByteCount, 0x34 for rxPacketCount),
# which is why enable ended up at 0x40 rather than right after the counters.
#
# The kernel is ap_ctrl_none, so it has no ap_ctrl register (0x00) at all.
set ::USR_OFF_LISTEN_PORT   0x10
set ::USR_OFF_RX_BYTE_LO    0x18
set ::USR_OFF_RX_BYTE_HI    0x1c
set ::USR_OFF_RX_PKT        0x30
set ::USR_OFF_ENABLE        0x40

# --- hex string parsing --------------------------------------------------------

# Inside expr {...} the substitution is done by expr's own parser, and it
# cannot glue the literal 0x onto a variable: expr {0x$ip_str} fails with
# "invalid bareword 0x". So build the string in quotes (where substitution
# does work) and coerce it to a number with + 0.
#
# Why not scan $s %x v:
#   * On a bad argument scan silently leaves v unset, and the failure surfaces
#     later as "can't read v" somewhere unrelated. The regexp below rejects
#     the input where the mistake actually is.
#   * The +0 form yields an unsigned value, so 0xFFFFFFFF reads back as
#     4294967295 rather than -1. That matters because axi_read32 feeds
#     counters and timestamps straight into integer comparisons.
#
# Tcl 8.5+ computes in 64 bits, so a 48-bit MAC should pass through intact.
# "Should" -- see _hex2words below for why we no longer rely on it for MACs.
proc _hex2int {s} {
     set s [string trim $s]
     regsub -nocase {^0x} $s "" s
     if {![regexp {^[0-9a-fA-F]+$} $s]} {
          error "expected a hex number without prefix, got: '$s'"
     }
     return [expr {"0x$s" + 0}]
}

# Split a hex string into low and high 32-bit words WITHOUT any arithmetic
# wider than 32 bits: the string is cut in two and each half parsed on its own.
#
# WHY THIS EXISTS. On the board a MAC of 000a35029de5 came back as
# 000035029de5 -- the 0x0a byte, which lives in the high word, was gone. Both
# the "writing" line and the "read back" line showed the truncated value, and
# network_configure still printed "write confirmed", because it compared the
# already-damaged value against itself. The stack's RTL is fine
# (network_control_s_axi.sv:435 writes int_mac_addr[63:32] from 0x1c), and the
# same parse on a desktop Tcl 8.6 yields the correct hi=0000000a -- so this is
# a property of the Tcl build inside that Vivado, not of the design.
#
# Rather than diagnose which Tcl does what, avoid the question: 48-bit values
# are never held in one integer. Correct on every Tcl, including the one that
# handles them properly.
#
# Returns a two-element list {lo hi}. For inputs of 8 hex digits or fewer the
# high word is 0, so this is safe for IPs too.
proc _hex2words {s} {
     set s [string trim $s]
     regsub -nocase {^0x} $s "" s
     if {![regexp {^[0-9a-fA-F]+$} $s]} {
          error "expected a hex number without prefix, got: '$s'"
     }
     set len [string length $s]
     if {$len > 16} {
          error "hex value too wide for 64 bits: '$s'"
     }
     if {$len <= 8} {
          return [list [expr {"0x$s" + 0}] 0]
     }
     set lo_str [string range $s end-7 end]
     set hi_str [string range $s 0 end-8]
     return [list [expr {"0x$lo_str" + 0}] [expr {"0x$hi_str" + 0}]]
}

# Format a {lo hi} pair back into a 12-digit hex string for printing, again
# without wide arithmetic. Used so the log shows what was really written.
proc _words2hex12 {lo hi} {
     return [format "%04x%08x" $hi $lo]
}

# --- low level access ----------------------------------------------------------

proc _jtag_axi_name {} {
     # Name of the AXI master in Hardware Manager: usually hw_axi_1, but it
     # depends on how jtag_axi is named in the BD.
     set axis [get_hw_axis -quiet]
     if {[llength $axis] == 0} {
          error "JTAG-to-AXI master not found. Is the device programmed? Does the design contain the jtag_axi IP?"
     }
     return [lindex $axis 0]
}

proc axi_write32 {addr value} {
     set hw_axi [_jtag_axi_name]
     set addr_hex [format %08x $addr]
     set data_hex [format %08x $value]

     # Transactions are reused, so delete an old one with the same name --
     # otherwise create_hw_axi_txn fails on the duplicate.
     set txn "wr_$addr_hex"
     if {[llength [get_hw_axi_txns -quiet $txn]] > 0} {
          delete_hw_axi_txn [get_hw_axi_txns $txn]
     }

     create_hw_axi_txn $txn $hw_axi -type write -address $addr_hex -data $data_hex -len 1
     run_hw_axi -quiet [get_hw_axi_txns $txn]
}

proc axi_read32 {addr} {
     set hw_axi [_jtag_axi_name]
     set addr_hex [format %08x $addr]

     set txn "rd_$addr_hex"
     if {[llength [get_hw_axi_txns -quiet $txn]] > 0} {
          delete_hw_axi_txn [get_hw_axi_txns $txn]
     }

     create_hw_axi_txn $txn $hw_axi -type read -address $addr_hex -len 1
     run_hw_axi -quiet [get_hw_axi_txns $txn]

     set data [get_property DATA [get_hw_axi_txns $txn]]
     return [_hex2int $data]
}

# --- network_krnl -------------------------------------------------------------

# ip_str  -- IP in hex without prefix, same byte order as host.cpp (there
#            local_IP is built as 0x0A01D498 for 10.1.212.152)
# mac_str -- MAC in hex, 48 bits
# n       -- channel number (1 = QSFP0, 2 = QSFP1, ...), see ouch_base_network.
proc network_configure {ip_str mac_str {arp 1} {n 1}} {
     set base [ouch_base_network $n]

     set ip  [_hex2int $ip_str]

     # MAC is handled as two 32-bit words end to end -- never as one 48-bit
     # integer. See _hex2words: on the board the high byte of the MAC was
     # silently lost, and because the comparison below used the same damaged
     # value on both sides, it still reported "write confirmed".
     lassign [_hex2words $mac_str] mac_lo mac_hi

     puts "network_krnl: ip=0x[format %08x $ip] mac=0x[_words2hex12 $mac_lo $mac_hi]"

     axi_write32 [expr {$base + $::NET_OFF_IP_ADDR}] $ip

     # mac_addr is a 64-bit argument, s_axilite exposes it as two words:
     # 0x18 = mac_addr[31:0], 0x1c = mac_addr[63:32]
     # (network_control_s_axi.sv:126-127).
     axi_write32 [expr {$base + $::NET_OFF_MAC_ADDR}]       $mac_lo
     axi_write32 [expr {$base + $::NET_OFF_MAC_ADDR + 4}]   $mac_hi

     axi_write32 [expr {$base + $::NET_OFF_ARP}] $arp

     # Read back. The ip_addr/mac_addr/arp registers in network_control_s_axi
     # are plain read/write, so the value read back confirms the JTAG write
     # landed. Without this check "the stack does not respond" is
     # indistinguishable from "the addresses were never written".
     set rd_ip  [axi_read32 [expr {$base + $::NET_OFF_IP_ADDR}]]
     set rd_lo  [axi_read32 [expr {$base + $::NET_OFF_MAC_ADDR}]]
     set rd_hi  [axi_read32 [expr {$base + $::NET_OFF_MAC_ADDR + 4}]]

     puts "  read back:  ip=0x[format %08x $rd_ip] mac=0x[_words2hex12 $rd_lo $rd_hi]"

     # Compare WORD BY WORD. The old code folded both halves into one integer
     # first, so a mangled high word compared equal to itself and the check
     # passed while the MAC was wrong.
     if {$rd_ip != $ip} {
          puts "  *** IP WRITE NOT CONFIRMED (wrote [format %08x $ip],"
          puts "      read [format %08x $rd_ip]) -- check ouch_base_network $n"
          puts "      and that the device is programmed with this bitstream"
          return 0
     }
     if {$rd_lo != $mac_lo || $rd_hi != $mac_hi} {
          puts "  *** MAC WRITE NOT CONFIRMED"
          puts "      lo: wrote [format %08x $mac_lo] read [format %08x $rd_lo]"
          puts "      hi: wrote [format %08x $mac_hi] read [format %08x $rd_hi]"
          puts "      The high word lives at offset 0x1c; if only it differs,"
          puts "      the 48-bit value was damaged before it reached AXI."
          return 0
     }
     puts "  write confirmed"

     # IMPORTANT: the stack latches the addresses not now but on the ap_start
     # edge -- in network_stack.sv that is
     #     assign set_ip_addr_valid  = ap_start_pulse;
     #     assign set_mac_addr_valid = ap_start_pulse;
     # So network_configure MUST be called BEFORE network_start.
     return 1
}

# Buffers for the TCP session tables. In Vitis these were cl::Buffer objects
# that XRT placed in DDR itself (host.cpp: buffer_r1/buffer_r2, 8 KB each);
# here the addresses are set by hand.
#
# The defaults are the start and the middle of the DDR4 c3 range (16 GB, bank
# DDR[3] -- the same one NETWORK_KRNL_MEM set in CMakeLists.txt for u200).
# build_bd.tcl prints the exact base address in its address map; if it is not
# 0, shift both values.
# n -- channel number. Both network_krnl instances share one DDR4 bank (first
# iteration, see build_bd.tcl), so different channels MUST point at different
# ranges -- otherwise the two stacks overwrite each other's session tables.
# The defaults below are valid for n=1 only; for n=2 pass a non-overlapping
# range (for example 0x80000000/0xC0000000).
proc network_set_buffers {{ptr0 0x00000000} {ptr1 0x40000000} {n 1}} {
     set base [ouch_base_network $n]

     puts "network_krnl\[$n\]: axi00_ptr0=0x[format %08x $ptr0] axi01_ptr0=0x[format %08x $ptr1]"

     axi_write32 [expr {$base + $::NET_OFF_AXI00_PTR}]     [expr {$ptr0 & 0xffffffff}]
     axi_write32 [expr {$base + $::NET_OFF_AXI00_PTR + 4}] [expr {($ptr0 >> 32) & 0xffffffff}]
     axi_write32 [expr {$base + $::NET_OFF_AXI01_PTR}]     [expr {$ptr1 & 0xffffffff}]
     axi_write32 [expr {$base + $::NET_OFF_AXI01_PTR + 4}] [expr {($ptr1 >> 32) & 0xffffffff}]
}

# Equivalent of enqueueTask(network_kernel). ap_ctrl_hs only.
proc network_start {{n 1}} {
     set addr [expr {[ouch_base_network $n] + $::NET_OFF_AP_CTRL}]

     # ap_start (bit 0) + auto_restart (bit 7): the stack must run
     # continuously rather than run once and stop.
     axi_write32 $addr 0x81

     set ctrl [axi_read32 $addr]
     puts "network_krnl\[$n\]: ap_ctrl=0x[format %02x $ctrl] (ap_start=[expr {$ctrl & 1}] ap_done=[expr {($ctrl >> 1) & 1}])"
}

# --- hls_ouch_krnl ------------------------------------------------------------

proc ouch_configure {listen_port {n 1}} {
     set base [ouch_base_user $n]
     puts "hls_ouch_krnl\[$n\]: listenPort=$listen_port"
     axi_write32 [expr {$base + $::USR_OFF_LISTEN_PORT}] $listen_port
}

# enable is written last -- it is the permission to start. See the comment
# about the ap_ctrl_none race in hls_ouch_krnl.cpp.
proc ouch_enable {{v 1} {n 1}} {
     puts "hls_ouch_krnl\[$n\]: enable=$v"
     axi_write32 [expr {[ouch_base_user $n] + $::USR_OFF_ENABLE}] $v
}

# What the OpenCL host could not do: read the output counters.
proc ouch_counters {{n 1}} {
     set base [ouch_base_user $n]

     set lo  [axi_read32 [expr {$base + $::USR_OFF_RX_BYTE_LO}]]
     set hi  [axi_read32 [expr {$base + $::USR_OFF_RX_BYTE_HI}]]
     set pkt [axi_read32 [expr {$base + $::USR_OFF_RX_PKT}]]

     set bytes [expr {($hi << 32) | $lo}]

     puts "\[$n\] rxByteCount   = $bytes"
     puts "\[$n\] rxPacketCount = $pkt"

     return [list $bytes $pkt]
}

# Periodic polling -- handy to see that traffic is flowing.
proc ouch_watch {{iterations 10} {delay_ms 1000} {n 1}} {
     for {set i 0} {$i < $iterations} {incr i} {
          set c [ouch_counters $n]
          puts "  \[$i\] bytes=[lindex $c 0] pkts=[lindex $c 1]"
          after $delay_ms
     }
}

# --- everything together ------------------------------------------------------

# Common bringup part: network (IP/MAC/buffers/ap_start) for channel n.
# n -- channel number (1 = QSFP0, 2 = QSFP1, ...).
proc _network_bringup {ip_str mac_str n} {
     network_configure $ip_str $mac_str 1 $n
     # The default ptr0/ptr1 are valid for n=1 only -- with two channels on
     # one DDR4 bank (see build_bd.tcl) the second channel must get a
     # non-overlapping range, otherwise the session tables clobber each other.
     if {$n == 1} {
          network_set_buffers 0x00000000 0x40000000 $n
     } else {
          network_set_buffers 0x80000000 0xC0000000 $n
     }
     network_start $n
}

# The order matters and mirrors host.cpp: configure the network first, start
# the stack, then configure the user kernel and only at the end allow it to
# run.
#
# ONLY for kernels with s_axi_control (hls_ouch_krnl). For hls_echo_krnl use
# echo_bringup below -- it has neither listenPort nor enable registers, and a
# write to a non-existent address in ctrl_interconnect ends up as DECERR.
proc ouch_bringup {listen_port ip_str mac_str {n 1}} {
     puts "=== bringup channel $n (ouch) ==="
     _network_bringup $ip_str $mac_str $n

     ouch_configure $listen_port $n
     ouch_enable 1 $n

     puts "=== done, channel $n is listening on port $listen_port ==="
     ouch_counters $n
}

# Bring up both gateway channels in one call (hls_ouch_krnl).
#   ouch_bringup_dual 7001 "0a01d498" "000a35029de5" 7002 "0a01d499" "000a35029de6"
proc ouch_bringup_dual {listen_port1 ip_str1 mac_str1 listen_port2 ip_str2 mac_str2} {
     ouch_bringup $listen_port1 $ip_str1 $mac_str1 1
     puts ""
     ouch_bringup $listen_port2 $ip_str2 $mac_str2 2
}

# The hls_echo_krnl counterpart of ouch_bringup: it has no s_axi_control (the
# listen port is hardcoded as LISTEN_PORT in hls_echo_krnl.cpp), so network
# only -- IP/MAC/ap_start. n -- channel number (1 = QSFP0, 2 = QSFP1, ...).
proc echo_bringup {ip_str mac_str {n 1}} {
     puts "=== bringup channel $n (echo) ==="
     _network_bringup $ip_str $mac_str $n
     # NOTE: says nothing about the listen port on purpose. For hls_echo_krnl
     # it is hardcoded (LISTEN_PORT); for hls_dual_echo_krnl it comes from
     # dual_echo_configure, which runs after this. Claiming a port number
     # here would be wrong for one of the two kernels.
     puts "=== done, channel $n network is up (IP/MAC latched, stack started) ==="
}

# Bring up both channels for hls_echo_krnl.
#   echo_bringup_dual "0a01d498" "000a35029de5" "0a01d499" "000a35029de6"
proc echo_bringup_dual {ip_str1 mac_str1 ip_str2 mac_str2} {
     echo_bringup $ip_str1 $mac_str1 1
     puts ""
     echo_bringup $ip_str2 $mac_str2 2
}

# =============================================================================
# hls_echo_probe_dual_krnl -- TCP stack latency measurement
# =============================================================================
#
# The kernel contains a client (port 0) and an echo server (port 1). A packet
# is sent on a trigger, travels around the loop through the cable and comes
# back. EIGHT raw timestamps are latched and the host computes the intervals:
# four small t on the kernel ports, and four big T from the axis_net_* taps that
# split "the network" into stack and wire. All eight come from ONE cycle counter
# in the wrapper, which is why the differences are meaningful.
#
# A bitstream built before the taps answers 0 on the four T registers; the host
# detects that and prints four intervals instead of seven rather than computing
# nonsense from zeros.
#
# Usage:
#     echo_bringup_dual 0a01d498 000a35029de5 0a01d499 000a35029de6
#     epd_configure 0a01d499 7001 64
#     epd_enable 1
#     epd_status                  ; # check that the connection opened
#     epd_net_status              ; # are the taps alive? (before measuring)
#     epd_collect 20              ; # 20 samples with statistics
#
# OFFSETS come from the HDL control wrapper, which is now the source of truth:
#     kernel/user_krnl/hls_echo_probe_dual_krnl/src/hdl/probe_control_s_axi.v
# The address map is spelled out in localparam there; these values are copied
# from it line by line.
#
# THEY CHANGED ON 12.08.2026 -- DO NOT REUSE OLD ONES. The kernel used to carry
# 18 x #pragma HLS INTERFACE s_axilite, which UG1393 forbids together with
# ap_ctrl_none: HLS silently latched the input scalars once in state2, right
# after reset, and writes over JTAG never reached the logic. For this kernel
# that was fatal rather than merely inconvenient -- triggerGo is meant to change
# on every sample, so the second measurement would never have started. The
# registers therefore moved into HDL, exactly as was done for
# hls_dual_echo_krnl.
#
# The old comment here explained that offsets could not be computed from the
# argument order, because HLS inserts an ap_vld register after every output
# (8-byte stride for inputs, 16 for outputs), and had to be read out of the
# generated *_hw.h. That whole problem is gone: the map is written by hand in
# the wrapper. Inputs keep the 8-byte stride so the layout stays familiar;
# read-only values are packed 4 bytes apart, since they are plain wires from the
# kernel with no ap_vld field.
set ::EPD_OFF_ENABLE        0x10
set ::EPD_OFF_SERVER_IP     0x18
set ::EPD_OFF_SERVER_PORT   0x20
set ::EPD_OFF_LISTEN_PORT   0x28
set ::EPD_OFF_MSG_BYTES     0x30
set ::EPD_OFF_TRIGGER_GO    0x38
set ::EPD_OFF_CONN_ATTEMPTS 0x40
set ::EPD_OFF_SENT          0x44
set ::EPD_OFF_RECV          0x48
set ::EPD_OFF_TIMEOUTS      0x4c
set ::EPD_OFF_ECHOES        0x50
set ::EPD_OFF_LISTEN_ATT    0x54
set ::EPD_OFF_PORT_STATE    0x58
set ::EPD_OFF_ECHO_RX       0x5c
set ::EPD_OFF_TS_REQUEST    0x60
set ::EPD_OFF_TS_ECHO_IN    0x64
set ::EPD_OFF_TS_ECHO_OUT   0x68
set ::EPD_OFF_TS_REPLY      0x6c
set ::EPD_OFF_SAMPLE_READY  0x70

# axis_net_* probe taps: the four big T points. These split NET_FWD (one number
# containing stack TX + CMAC + cable + CMAC + stack RX) into three parts:
#
#     t1' ─ stack 0 TX ─ T1' ─ CMAC+cable+CMAC ─ T2' ─ stack 1 RX ─ t2'
#
# EXT_* (between two T points) is what code cannot improve -- CMAC is a black
# box, ~150-200 ns per datasheet, the cable ~5 ns/m. Everything else can be.
#
# minWords is RW: the frame filter threshold in 512-bit words. epd_configure
# computes it from msgBytes, there is no need to set it by hand.
set ::EPD_OFF_MIN_WORDS     0x74
set ::EPD_OFF_TS_NET_TX_A   0x78
set ::EPD_OFF_TS_NET_RX_B   0x7c
set ::EPD_OFF_TS_NET_TX_B   0x80
set ::EPD_OFF_TS_NET_RX_A   0x84
set ::EPD_OFF_NF_COUNT_A    0x88
set ::EPD_OFF_NF_COUNT_B    0x8c
set ::EPD_OFF_NF_DROP_A     0x90
set ::EPD_OFF_NF_DROP_B     0x94

# ap_clk period, ns. Must match DEV_FREQ_MHZ in devices/<board>/device.tcl.in.
# 165 MHz -> 6.061 ns. If the frequency changes, fix it here too, otherwise the
# conversion to nanoseconds lies -- silently, which is the worst kind.
#
# Was 5.882 (170 MHz) until 11.08.2026, lowered because timing stopped closing
# once hls_dual_echo_krnl moved to ap_ctrl_hs (WNS went to -0.010).
set ::EPD_CLK_NS 6.061

# Trigger counter: the edge is detected by a CHANGE in value, so there is no
# need to clear the register between samples.
set ::EPD_TRIG 0

# Parameters. serverIp is hex without prefix, same as in network_configure.
# listenPort always equals serverPort: the client connects where the server
# listens.
proc epd_configure {serverIp serverPort msgBytes {n 1}} {
     set base [ouch_base_user $n]

     # Two independent reasons the axis_net_* taps need msgBytes >= 32, both
     # covered by the same number:
     #
     #   * below 11 bytes our frame becomes single-word (54+msgBytes <= 64) and
     #     is indistinguishable BY LENGTH from a bare ACK;
     #   * below 10 bytes there is nowhere to put the filter marker, which the
     #     kernel writes into payload[4..9].
     #
     # Neither would fail loudly: the taps would time-stamp the wrong frame and
     # return plausible numbers, which is worse than an error. The sweep starts
     # at 64 bytes anyway, so refusing here costs nothing.
     if {$msgBytes < 32} {
          puts "epd\[$n\]: *** msgBytes=$msgBytes is below 32 -- REFUSED."
          puts "      The axis_net_* filter needs both a frame longer than one"
          puts "      512-bit word (to tell it from a bare ACK) and room for the"
          puts "      marker in payload\[4..9\]. Below 32 bytes the four T"
          puts "      timestamps would silently latch on the wrong frame."
          puts "      Use 32 or more."
          return 0
     }

     # Filter threshold, in 512-bit words: ceil(frame_bytes / 64), where the
     # frame is 14 (Ethernet) + 20 (IP) + 20 (TCP) + msgBytes. Written together
     # with msgBytes so a size sweep never leaves the threshold stale -- a
     # threshold too high means the filter drops OUR frame too, and then the
     # timestamps simply stop updating.
     set frameBytes [expr {14 + 20 + 20 + $msgBytes}]
     set minWords   [expr {($frameBytes + 63) / 64}]

     puts "epd\[$n\]: server=0x$serverIp:$serverPort msg=$msgBytes bytes"
     puts "epd\[$n\]: frame=$frameBytes bytes -> minWords=$minWords"

     set sip [_hex2int $serverIp]
     axi_write32 [expr {$base + $::EPD_OFF_SERVER_IP}]   $sip
     axi_write32 [expr {$base + $::EPD_OFF_SERVER_PORT}] $serverPort
     axi_write32 [expr {$base + $::EPD_OFF_LISTEN_PORT}] $serverPort
     axi_write32 [expr {$base + $::EPD_OFF_MSG_BYTES}]   $msgBytes
     axi_write32 [expr {$base + $::EPD_OFF_MIN_WORDS}]   $minWords

     # Verify by reading back: without this, "the kernel does not respond" is
     # indistinguishable from "the parameters were never written".
     set rd [axi_read32 [expr {$base + $::EPD_OFF_MSG_BYTES}]]
     if {$rd != $msgBytes} {
          puts "  *** WRITE NOT CONFIRMED (msgBytes=$rd, expected $msgBytes)"
          puts "      check ouch_base_user $n and that this bitstream is loaded"
          return 0
     }
     # minWords is checked separately, and on purpose: it lives in a register
     # block added later than the rest, so a bitstream built before the taps
     # existed answers 0 here while msgBytes above reads back correctly. That
     # combination means "old bitstream", not "bad write", and saying so beats
     # letting the T timestamps stay at zero with no explanation.
     set rdw [axi_read32 [expr {$base + $::EPD_OFF_MIN_WORDS}]]
     if {$rdw != $minWords} {
          puts "  *** minWords NOT CONFIRMED (read $rdw, expected $minWords)"
          puts "      msgBytes wrote fine, so the base address is right. Most"
          puts "      likely this bitstream predates the axis_net_* taps: the"
          puts "      four t points still work, the four T points will read 0."
          return 0
     }
     puts "  write confirmed"
     return 1
}

# enable LAST: before it the kernel does not touch the stack ports, because
# the serverIp/serverPort registers may not have been written yet.
proc epd_enable {{v 1} {n 1}} {
     puts "epd\[$n\]: enable=$v"
     axi_write32 [expr {[ouch_base_user $n] + $::EPD_OFF_ENABLE}] $v
}

# Counters: they show which stage things got stuck at.
proc epd_status {{n 1}} {
     set base [ouch_base_user $n]
     set att [axi_read32 [expr {$base + $::EPD_OFF_CONN_ATTEMPTS}]]
     set snt [axi_read32 [expr {$base + $::EPD_OFF_SENT}]]
     set ech [axi_read32 [expr {$base + $::EPD_OFF_ECHOES}]]
     set rcv [axi_read32 [expr {$base + $::EPD_OFF_RECV}]]
     set tmo [axi_read32 [expr {$base + $::EPD_OFF_TIMEOUTS}]]
     set rdy [axi_read32 [expr {$base + $::EPD_OFF_SAMPLE_READY}]]
     set lat [axi_read32 [expr {$base + $::EPD_OFF_LISTEN_ATT}]]
     set pst [axi_read32 [expr {$base + $::EPD_OFF_PORT_STATE}]]
     set erx [axi_read32 [expr {$base + $::EPD_OFF_ECHO_RX}]]

     puts "epd\[$n\]: connAttempts=$att sent=$snt echoRx=$erx echoes=$ech recv=$rcv timeouts=$tmo ready=$rdy"
     puts "epd\[$n\]: server listen: attempts=$lat state=[_epd_state $pst]"

     # Diagnostics: where exactly the chain broke. The server-side listen state
     # comes first -- if the port never opened, nothing downstream can work,
     # and before portState existed this was indistinguishable from a dead link.
     if {$pst == 0} {
          puts "  -> the server has not requested a listen port: enable=0?"
     } elseif {$pst == 1} {
          puts "  -> the server asked for a listen port and the stack has not"
          puts "     answered (attempts=$lat, and it retries on a timeout)."
          puts "     Check that echo_bringup_dual ran BEFORE epd_enable, then vio_dump."
     } elseif {$att == 0} {
          puts "  -> the client never tried to open a connection: enable=0?"
     } elseif {$snt == 0 && $att > 3} {
          puts "  -> connection did not open even though the port is OPEN."
          puts "     Check addressing (same /24, different last octets) and vio_dump."
     } elseif {$snt > 0 && $erx == 0} {
          puts "  -> the request never reached port 1: link, cable or CMAC placement"
          # The taps split this further than the kernel counters can: if the tap
          # on channel A counted the frame, it did leave the FPGA and the fault
          # is in the cable or the far CMAC; if it did not, the request never got
          # past the local stack. Worth one extra command before reaching for
          # vio_dump.
          puts "     epd_net_status tells \"left the FPGA\" from \"never got out\""
     } elseif {$erx > 0 && $ech == 0} {
          puts "  -> the echo RECEIVED the request but never sent a reply."
          puts "     That is inside the kernel, not the network: the echo is stuck"
          puts "     waiting for tx_status from stack 1. Report this to us."
     } elseif {$ech > 0 && $rcv == 0} {
          puts "  -> the echo replied but the reply never came back: reverse path"
     }
     return [list $att $snt $ech $rcv $tmo $rdy $lat $pst $erx]
}

proc _epd_state {v} {
     switch -- $v {
          0 { return "0(no-request)" }
          1 { return "1(requested)" }
          2 { return "2(OPEN)" }
          default { return "$v(?)" }
     }
}

# One sample: pull the trigger, wait for sampleReady, read the eight values.
#
# There is no read race by construction: until the trigger is pulled again no
# new packet is sent and the registers do not change.
#
# Returns {t1p t2p t1 t2 T1p T2p T1 T2}, or an empty list on timeout.
#
# The four T values come from the axis_net_* taps and are latched by the SAME
# cycle_counter as the four t values -- that is the whole reason the taps live
# in the wrapper rather than in a separate sniffer kernel. Reading them costs
# four more JTAG transactions per sample, so a sample now costs ten rather than
# six; epd_calibrate's estimate scales accordingly.
#
# No read race, same as before: until the trigger is pulled again no new packet
# is sent, so none of the eight registers move while they are being read. The
# T points are covered by the same argument -- they belong to the same packet
# because there is only ever one packet in flight.
proc epd_sample {{n 1} {timeout_ms 500}} {
     set base [ouch_base_user $n]

     # Writing triggerGo clears sampleReady and launches the packet -- one
     # transaction doing two things.
     incr ::EPD_TRIG
     axi_write32 [expr {$base + $::EPD_OFF_TRIGGER_GO}] $::EPD_TRIG

     set t0 [clock milliseconds]
     while {1} {
          if {[axi_read32 [expr {$base + $::EPD_OFF_SAMPLE_READY}]] == 1} break
          if {[expr {[clock milliseconds] - $t0}] > $timeout_ms} {
               return {}
          }
     }

     set t1p [axi_read32 [expr {$base + $::EPD_OFF_TS_REQUEST}]]
     set t2p [axi_read32 [expr {$base + $::EPD_OFF_TS_ECHO_IN}]]
     set t1  [axi_read32 [expr {$base + $::EPD_OFF_TS_ECHO_OUT}]]
     set t2  [axi_read32 [expr {$base + $::EPD_OFF_TS_REPLY}]]

     set T1p [axi_read32 [expr {$base + $::EPD_OFF_TS_NET_TX_A}]]
     set T2p [axi_read32 [expr {$base + $::EPD_OFF_TS_NET_RX_B}]]
     set T1  [axi_read32 [expr {$base + $::EPD_OFF_TS_NET_TX_B}]]
     set T2  [axi_read32 [expr {$base + $::EPD_OFF_TS_NET_RX_A}]]

     return [list $t1p $t2p $t1 $t2 $T1p $T2p $T1 $T2]
}

# Frame-filter counters from the four axis_net_* taps.
#
# NOT a measurement -- a liveness check, and the pair matters more than either
# number alone:
#
#   * count grows, drop grows      -- normal: our frames pass, ARP/ACK dropped
#   * count = 0, drop grows        -- the filter rejects EVERYTHING, our frame
#                                     included. minWords too high for msgBytes.
#   * count = 0, drop = 0          -- the tap is dead: wired to the wrong pins,
#                                     or this bitstream predates the taps.
#
# Without this pair, "the T timestamps did not update" is indistinguishable
# from "the filter is too strict" -- the same reasoning that put listenAttempts
# and portState into the kernel.
proc epd_net_status {{n 1}} {
     set base [ouch_base_user $n]
     set ca [axi_read32 [expr {$base + $::EPD_OFF_NF_COUNT_A}]]
     set cb [axi_read32 [expr {$base + $::EPD_OFF_NF_COUNT_B}]]
     set da [axi_read32 [expr {$base + $::EPD_OFF_NF_DROP_A}]]
     set db [axi_read32 [expr {$base + $::EPD_OFF_NF_DROP_B}]]
     set mw [axi_read32 [expr {$base + $::EPD_OFF_MIN_WORDS}]]

     # Сколько пакетов ядро вообще отправило. Без этого числа passed=0 не
     # истолковать: см. ниже.
     set snt [axi_read32 [expr {$base + $::EPD_OFF_SENT}]]

     puts "epd\[$n\]: net taps: minWords=$mw (sent=$snt)"
     puts "epd\[$n\]:   channel A (QSFP0): passed=$ca dropped=$da"
     puts "epd\[$n\]:   channel B (QSFP1): passed=$cb dropped=$db"

     foreach {ch cnt drp} [list A $ca $da B $cb $db] {
          if {$cnt == 0 && $drp == 0} {
               puts "  -> channel $ch tap sees NO traffic at all. Either this"
               puts "     bitstream has no taps, or config_sp did not route"
               puts "     axis_net_* through the wrapper on this channel."
          } elseif {$cnt == 0 && $snt == 0} {
               # НОРМА, а не отказ. Это состояние сразу после epd_enable:
               # ARP и SYN/SYN-ACK уже прошли по проводу (односоловные кадры,
               # фильтр их и должен отсеивать), а НАШЕГО кадра ещё не было --
               # ни одного замера не запускали.
               #
               # Раньше эта ветка попадала под "drops every frame" и советовала
               # понизить minWords. Ложная тревога срабатывала у каждого, кто
               # следует инструкции: она велит звать epd_net_status ДО первого
               # epd_measure, то есть ровно здесь.
               puts "  -> channel $ch: no measurement has run yet (sent=0), so"
               puts "     only ARP/SYN went through -- they are supposed to be"
               puts "     dropped. This is normal. Re-check after epd_measure."
          } elseif {$cnt == 0} {
               puts "  -> channel $ch drops every frame, ours included:"
               puts "     minWords=$mw is too high. Re-run epd_configure."
          }
     }
     return [list $ca $cb $da $db $mw]
}

# Subtraction modulo 2^32 -- the same as in hardware. Needed because the
# clock-cycle counter wraps roughly every 25 s at 170 MHz, and a difference
# across the wrap must stay correct.
proc _epd_sub32 {a b} { return [expr {($a - $b) & 0xFFFFFFFF}] }

# Computes the intervals from the raw timestamps.
#
# Returns {rtt fwd echo rev  s0tx extA s1rx s1tx extB s0rx} in clock cycles.
# The first four are unchanged and stay first on purpose: callers that only
# want them keep working with lassign as they did.
#
# THE FULL DECOMPOSITION OF THE LOOP, seven terms instead of three:
#
#     RTT = STACK_0_TX + EXT_A + STACK_1_RX + ECHO
#                      + STACK_1_TX + EXT_B + STACK_0_RX
#
#   STACK_0_TX = T1' - t1'   stack of port 0: TOE + IP + merge, request to wire
#   EXT_A      = T2' - T1'   CMAC0 + SerDes + cable + SerDes + CMAC1
#   STACK_1_RX = t2' - T2'   stack of port 1: ip_handler + TOE RX + delivery
#   ECHO       = t1  - t2'   the echo inside the kernel (a few cycles)
#   STACK_1_TX = T1  - t1    stack of port 1 sending the reply
#   EXT_B      = T2  - T1    the wire back
#   STACK_0_RX = t2  - T2    stack of port 0 receiving the reply
#
# The stacks decompose into FOUR values, not two: network_krnl_1 and
# network_krnl_2 are physically separate instances, each with its own TX and RX
# path. Folding them into one "stack time" would lose exactly the asymmetry we
# are looking for.
#
# NO "-1" CORRECTION IS APPLIED, and that is deliberate. All eight points are
# stamped by ONE cycle_counter in the wrapper, so any latency shared between
# event and latch cancels in the difference. The schematic in the artefact
# writes these formulas as "T1' - t1' - 1"; that 1 belongs to the REGISTERED
# tap variant (skid buffer, +1 cycle in the path). Ours is a plain passthrough
# with no register, so subtracting one would introduce a one-cycle (6 ns) error
# where none exists.
#
# There IS a shift that does not cancel: the t points are stamped off the ap_vld
# of a registered HLS output, the T points off tvalid&tready&tlast straight from
# the bus. Different paths, so t may lag T by a cycle. It affects only the MIXED
# intervals (the four STACK_*, where T-t is subtracted); the homogeneous ones
# are untouched -- EXT_* comes from two T values, RTT and ECHO from two t.
# Do not guess its size: it equals the discrepancy of STACK_0_TX+EXT_A+STACK_1_RX
# against NET_FWD, which is known independently from the four t points. That is
# what epd_measure prints as "residual". Once measured on live hardware, it
# becomes a constant here -- with a number taken from the measurement, not from
# a guess.
#
# NOTE ON THE OLD BALANCE CHECK. fwd+echo+rev == rtt is an ALGEBRAIC IDENTITY
# for any four numbers: (t2'-t1') + (t1-t2') + (t2-t1) collapses to (t2-t1'),
# and it holds under modulo-2^32 arithmetic too. So it can only fail if a
# register was read torn -- it does NOT validate that the values belong to the
# same packet. The same is true of the seven-term sum. What is NOT an identity
# is the residual above: it mixes two independent stamping paths, so it carries
# real information.
proc epd_intervals {sample} {
     lassign $sample t1p t2p t1 t2 T1p T2p T1 T2
     set rtt [_epd_sub32 $t2  $t1p]
     set fwd [_epd_sub32 $t2p $t1p]
     set ech [_epd_sub32 $t1  $t2p]
     set rev [_epd_sub32 $t2  $t1]

     # A bitstream without the taps answers 0 on all four T registers. Return
     # the four classic intervals and empty slots rather than nonsense: a
     # modulo subtraction of zero would produce huge plausible-looking numbers
     # (0 - t1' wraps to ~2^32), and those are worse than a visible gap.
     if {$T1p == 0 && $T2p == 0 && $T1 == 0 && $T2 == 0} {
          return [list $rtt $fwd $ech $rev {} {} {} {} {} {}]
     }

     set s0tx [_epd_sub32 $T1p $t1p]
     set extA [_epd_sub32 $T2p $T1p]
     set s1rx [_epd_sub32 $t2p $T2p]
     set s1tx [_epd_sub32 $T1  $t1]
     set extB [_epd_sub32 $T2  $T1]
     set s0rx [_epd_sub32 $t2  $T2]

     return [list $rtt $fwd $ech $rev $s0tx $extA $s1rx $s1tx $extB $s0rx]
}

# One sample with printout. Also checks the balance: the parts must add up to
# the full loop, otherwise the timestamps come from different packets.
proc epd_measure {{n 1}} {
     set s [epd_sample $n]
     if {[llength $s] == 0} {
          puts "epd: sample failed (no sampleReady within the timeout)"
          epd_status $n
          return {}
     }
     lassign $s t1p t2p t1 t2 T1p T2p T1 T2
     set iv [epd_intervals $s]
     lassign $iv rtt fwd ech rev s0tx extA s1rx s1tx extB s0rx
     set ns $::EPD_CLK_NS

     # Raw counter values first. They are what the hardware actually latched;
     # everything below is arithmetic the host does on them. Printing both
     # means a suspicious interval can be re-derived by hand instead of
     # being taken on trust -- and the wrap case (t2 < t1') stays visible
     # rather than hidden behind a modulo subtraction.
     puts "  raw t: t1'=$t1p t2'=$t2p t1=$t1 t2=$t2"
     puts "  raw T: T1'=$T1p T2'=$T2p T1=$T1 T2=$T2"
     if {$t2 < $t1p} {
          puts "       (counter wrapped between t1' and t2 -- normal, the"
          puts "        subtraction below is modulo 2^32)"
     }

     puts [format "  RTT     %6d cycles  %9.1f ns" $rtt [expr {$rtt*$ns}]]
     puts [format "  NET_FWD %6d          %9.1f" $fwd [expr {$fwd*$ns}]]
     puts [format "  ECHO    %6d          %9.1f" $ech [expr {$ech*$ns}]]
     puts [format "  NET_REV %6d          %9.1f" $rev [expr {$rev*$ns}]]

     # No "balance" line for fwd+echo+rev == rtt on purpose: it is an identity
     # (see epd_intervals), so printing it every time advertised a check that
     # cannot fail on real data. It is still worth guarding, because a torn
     # JTAG read WOULD break it -- but that is a transport fault, so say so.
     if {[expr {$fwd + $ech + $rev}] != $rtt} {
          puts "  *** TORN READ: fwd+echo+rev != rtt, which is arithmetically"
          puts "      impossible -- a register was read mid-update. Discard."
     }

     if {$s0tx eq ""} {
          puts "  (no axis_net_* taps in this bitstream -- four t points only."
          puts "   The seven-term decomposition needs the T points; rebuild with"
          puts "   the taps to get it.)"
     } else {
          puts ""
          puts "  --- decomposition, seven terms ---"
          puts [format "  STACK_0_TX %6d cycles %9.1f ns   request into the wire (port 0)" \
                    $s0tx [expr {$s0tx*$ns}]]
          puts [format "  EXT_A      %6d        %9.1f      CMAC+cable+CMAC, forward" \
                    $extA [expr {$extA*$ns}]]
          puts [format "  STACK_1_RX %6d        %9.1f      wire to application (port 1)" \
                    $s1rx [expr {$s1rx*$ns}]]
          puts [format "  ECHO       %6d        %9.1f      inside the kernel" \
                    $ech [expr {$ech*$ns}]]
          puts [format "  STACK_1_TX %6d        %9.1f      reply into the wire (port 1)" \
                    $s1tx [expr {$s1tx*$ns}]]
          puts [format "  EXT_B      %6d        %9.1f      CMAC+cable+CMAC, reverse" \
                    $extB [expr {$extB*$ns}]]
          puts [format "  STACK_0_RX %6d        %9.1f      wire to measurer (port 0)" \
                    $s0rx [expr {$s0rx*$ns}]]

          # THE RESIDUAL. This is the one check here that is not an identity,
          # and the number the whole tap exercise hinges on.
          #
          # STACK_0_TX + EXT_A + STACK_1_RX must equal NET_FWD, which is known
          # independently from the four t points alone. The t and T points are
          # stamped off DIFFERENT paths (ap_vld of a registered HLS output vs
          # tvalid&tready&tlast straight off the bus), so a small constant
          # residual -- a cycle or so -- is expected and is exactly the
          # correction to fold into the four STACK_* values later.
          #
          # A LARGE residual means something else: the filter latched the wrong
          # frame. Then check epd_net_status, and read the "foreign traffic"
          # section of docs/latency_net_probe_design.md.
          set res_f [expr {($s0tx + $extA + $s1rx) - $fwd}]
          set res_r [expr {($s1tx + $extB + $s0rx) - $rev}]
          puts ""
          puts [format "  residual fwd %+d cycles, rev %+d  (t-vs-T stamping shift;" \
                    $res_f $res_r]
          puts "                 a cycle or two is expected, tens mean the filter"
          puts "                 caught the wrong frame -- run epd_net_status)"
     }

     # Raw values first, then the intervals: callers that only want the
     # intervals can still lrange them out, and nothing silently discards
     # the raw data.
     return [concat [list $t1p $t2p $t1 $t2 $T1p $T2p $T1 $T2] $iv]
}

# Raw samples as CSV, for analysis outside Vivado.
#
# Prints one line per sample with BOTH the raw counters and the derived
# intervals, so a spreadsheet or a script can recompute everything and check
# the host arithmetic instead of trusting it. Failed samples are still
# printed, flagged in the status column -- silently dropping them would hide
# exactly the cases worth looking at.
#
# status is TIMEOUT (no sampleReady) or TORN (a register read caught mid-update;
# arithmetically impossible otherwise). It is NOT a plausibility check: an
# outlier with a perfectly consistent sum still reads as ok, so judge the
# numbers by their spread, not by this column.
#
# Redirect it to a file the usual Tcl way if you want one:
#     set fh [open C:/epd_raw.csv w]; puts $fh [epd_raw 50]; close $fh
proc epd_raw {count {n 1}} {
     # Eight raw stamps, then the four classic intervals, then the six from the
     # taps. Empty tap columns mean a bitstream without them -- see
     # epd_intervals, which refuses to fabricate numbers from zeros.
     set hdr "sample,t1p,t2p,t1,t2,T1p,T2p,T1,T2"
     append hdr ",rtt,net_fwd,echo,net_rev"
     append hdr ",stack0_tx,ext_a,stack1_rx,stack1_tx,ext_b,stack0_rx"
     append hdr ",ns_rtt,status"
     set out $hdr
     puts $out

     # Column count, so a TIMEOUT row lines up with the header instead of being
     # counted by hand. 21 fields = 1 + 8 + 4 + 6 + 2.
     #
     # The sample index and the status both carry a value, so between them go
     # ncol-2 EMPTY fields, which needs ncol-1 commas -- one to close the index
     # and one to open the status. Off by one here is not cosmetic: a short row
     # shifts every column after it, so a spreadsheet reads net_rev as echo and
     # the numbers stay plausible.
     set ncol [llength [split $hdr ","]]
     set empty [string repeat "," [expr {$ncol - 1}]]

     for {set i 0} {$i < $count} {incr i} {
          set s [epd_sample $n]
          if {[llength $s] == 0} {
               set line "$i${empty}TIMEOUT"
               puts $line
               append out "\n$line"
               continue
          }
          lassign $s t1p t2p t1 t2 T1p T2p T1 T2
          lassign [epd_intervals $s] rtt fwd ech rev s0tx extA s1rx s1tx extB s0rx
          set ok [expr {($fwd + $ech + $rev) == $rtt ? "ok" : "TORN"}]
          set line [format "%d,%u,%u,%u,%u,%u,%u,%u,%u,%d,%d,%d,%d,%s,%s,%s,%s,%s,%s,%.1f,%s" \
                        $i $t1p $t2p $t1 $t2 $T1p $T2p $T1 $T2 \
                        $rtt $fwd $ech $rev \
                        $s0tx $extA $s1rx $s1tx $extB $s0rx \
                        [expr {$rtt * $::EPD_CLK_NS}] $ok]
          puts $line
          append out "\n$line"
     }
     return $out
}

# How much one JTAG transaction costs. Worth knowing before collecting
# statistics: it determines how many samples are realistic.
proc epd_calibrate {{n 1} {iters 100}} {
     set base [ouch_base_user $n]
     set t0 [clock milliseconds]
     for {set i 0} {$i < $iters} {incr i} {
          axi_read32 [expr {$base + $::EPD_OFF_SAMPLE_READY}]
     }
     set dt [expr {[clock milliseconds] - $t0}]
     set per [expr {double($dt)/$iters}]
     puts [format "JTAG: %d reads in %d ms = %.2f ms per transaction" $iters $dt $per]
     # Ten transactions per sample since the axis_net_* taps were added: one
     # trigger write, one sampleReady poll, four t reads, four T reads. It was
     # six before the taps -- if an old estimate is being compared against,
     # that is the difference.
     puts [format "      one sample (~10 transactions) is about %.0f ms" [expr {$per*10}]]
     return $per
}

# A series of samples with a summary. Keep count in the tens or hundreds:
# that is enough to see the order of magnitude and the spread. Thousands are
# only needed for the tail of the distribution, and that belongs to the
# under-load measurement, which needs a different mode.
# Warm-up samples discarded before the statistics. Not a fudge factor: the
# first packets after epd_enable share the pipe with connection setup, and
# their timestamps are legitimately different from steady state.
#
#   * SYN / SYN-ACK of the client connection,
#   * the first ARP exchange (both stacks learn each other's MAC),
#   * the very first pass through TOE, when its session tables in DDR4 are
#     still cold.
#
# Three is enough for that -- the setup traffic is a handful of frames, not a
# ramp. Raising it hides real behaviour instead of noise, so leave it at three
# unless the raw CSV shows a longer transient.
#
# epd_raw does NOT skip them: it prints every sample with its status, and the
# whole point of the raw dump is to see what the aggregate dropped.
set ::EPD_WARMUP 3

proc epd_collect {count {n 1}} {
     # Order matches epd_intervals: the four classic intervals first, then the
     # six from the axis_net_* taps. A blank name is a group separator in the
     # printout, not a series.
     set names {RTT NET_FWD ECHO NET_REV
                STACK_0_TX EXT_A STACK_1_RX STACK_1_TX EXT_B STACK_0_RX}
     set nser  [llength $names]
     set data  {}
     for {set k 0} {$k < $nser} {incr k} { lappend data {} }
     set bad 0
     set no_taps 0
     set raw_t1p {}
     set raw_t2  {}

     # Warm-up: fire and throw away, before anything is accumulated.
     for {set w 0} {$w < $::EPD_WARMUP} {incr w} {
          epd_sample $n
     }

     for {set i 0} {$i < $count} {incr i} {
          set s [epd_sample $n]
          if {[llength $s] == 0} { incr bad; continue }
          set iv [epd_intervals $s]
          lassign $iv rtt fwd ech rev
          # Drop torn reads (see epd_intervals: the sum is an identity, so
          # this only trips on a register read caught mid-update).
          if {[expr {$fwd + $ech + $rev}] != $rtt} { incr bad; continue }

          # A bitstream without the taps returns empty tap slots. Accumulate
          # the four classic series anyway -- they are just as valid as before
          # the taps existed -- and count the samples so the printout can say
          # WHY the six tap rows are missing instead of showing empty stats.
          set have_taps [expr {[lindex $iv 4] ne ""}]
          if {!$have_taps} { incr no_taps }

          set lim [expr {$have_taps ? $nser : 4}]
          for {set k 0} {$k < $lim} {incr k} {
               lset data $k [concat [lindex $data $k] [lindex $iv $k]]
          }
          lappend raw_t1p [lindex $s 0]
          lappend raw_t2  [lindex $s 3]
     }

     set got [llength [lindex $data 0]]
     puts ""
     puts "=== $got samples out of $count (discarded: $bad, warm-up: $::EPD_WARMUP) ==="
     if {$got == 0} { epd_status $n; return }
     if {$no_taps > 0} {
          puts "    $no_taps of them without axis_net_* taps (T points read 0):"
          puts "    the four rows below are valid, the seven-term decomposition"
          puts "    is not available. Rebuild with the taps to get it."
     }

     puts [format "%-11s %8s %8s %8s %9s   %s" \
               "" "min" "med" "max" "mean" "ns (mean)"]
     for {set k 0} {$k < $nser} {incr k} {
          set v [lsort -integer [lindex $data $k]]
          set cnt [llength $v]
          # Skip a series with no data: that is the tap rows on a bitstream
          # without them. Printing zeros would read as "measured 0 cycles".
          if {$cnt == 0} { continue }
          # Blank line between the classic four and the decomposition, so the
          # two groups are not misread as one flat list of comparable numbers.
          if {$k == 4} {
               puts "            --- decomposition (needs the axis_net_* taps) ---"
          }
          set mn [lindex $v 0]
          set mx [lindex $v end]
          set md [lindex $v [expr {$cnt / 2}]]
          set sum 0
          foreach x $v { incr sum $x }
          set avg [expr {double($sum)/$cnt}]
          puts [format "%-11s %8d %8d %8d %9.1f   %9.1f" \
                    [lindex $names $k] $mn $md $mx $avg \
                    [expr {$avg*$::EPD_CLK_NS}]]
     }

     # Free checks the decomposition makes possible. Both are about symmetry,
     # and both are informative rather than pass/fail -- see
     # docs/latency_net_probe_design.md.
     if {[llength [lindex $data 4]] > 0} {
          set n_ok [llength [lindex $data 4]]
          set med {}
          for {set k 4} {$k < $nser} {incr k} {
               set v [lsort -integer [lindex $data $k]]
               lappend med [lindex $v [expr {[llength $v] / 2}]]
          }
          lassign $med m_s0tx m_extA m_s1rx m_s1tx m_extB m_s0rx

          puts ""
          # CMAC_ONE = (EXT_A + EXT_B - 2*CABLE) / 4. CABLE is ~5 ns/m, i.e.
          # under one cycle, so it is a second-order correction and is dropped
          # here. No separate calibration build is needed: the external deltas
          # give CMAC from this very measurement.
          set cmac_one [expr {($m_extA + $m_extB) / 4.0}]
          puts [format "CMAC_ONE   ~%.1f cycles (%.1f ns) -- one side of one CMAC," \
                    $cmac_one [expr {$cmac_one*$::EPD_CLK_NS}]]
          puts "                    from (EXT_A+EXT_B)/4, cable ignored (<1 cycle)"

          # E2E: the gateway budget for one pass, cable to cable -- receive on
          # one port, process, transmit on the other. This is the number the
          # whole exercise is for. ECHO stands in for the gateway logic, which
          # is not written yet, so this is the FLOOR, not a prediction.
          set e2e [expr {$m_s1rx + $m_s1tx + 2*$cmac_one}]
          puts [format "E2E floor  ~%.1f cycles (%.1f ns) -- one gateway pass," \
                    $e2e [expr {$e2e*$::EPD_CLK_NS}]]
          puts "                    STACK_1_RX + STACK_1_TX + 2*CMAC_ONE, logic = 0"

          # EXT_A vs EXT_B: the two CMAC sides. They are NOT obliged to match
          # here -- port 0 sits on QPLL0, port 1 on QPLL1, different GT quads.
          if {$m_extA > 0 && $m_extB > 0} {
               set r [expr {double($m_extA)/$m_extB}]
               if {$r > 1.5 || $r < 0.667} {
                    puts [format "  note: EXT_A (%d) and EXT_B (%d) differ by more than 1.5x." \
                              $m_extA $m_extB]
                    puts "        Not necessarily wrong -- different GT quads and QPLLs --"
                    puts "        but check epd_net_status that both taps see traffic."
               }
          }

          # STACK_0_RX vs STACK_1_RX: the SAME network_krnl in two instances.
          # A real divergence here means external influence -- DDR4 contention,
          # SLR placement -- not stack asymmetry.
          if {$m_s0rx > 0 && $m_s1rx > 0} {
               set r [expr {double($m_s0rx)/$m_s1rx}]
               if {$r > 1.5 || $r < 0.667} {
                    puts [format "  note: STACK_0_RX (%d) vs STACK_1_RX (%d) differ by >1.5x," \
                              $m_s0rx $m_s1rx]
                    puts "        yet these are the same network_krnl in two instances."
                    puts "        Suspect external influence: DDR4 contention, SLR placement."
                    puts "        Check make -f Makefile.vivado report."
               }
          }
          puts "($n_ok samples with taps)"
     }

     # THIS is the check that catches a bad sample -- not the sum, which is an
     # identity (see epd_intervals). A single stray packet in the pipe shows up
     # as max far above the median; the mean alone would just drift and hide it.
     set rtts [lsort -integer [lindex $data 0]]
     set rmed [lindex $rtts [expr {$got / 2}]]
     set rmax [lindex $rtts end]
     if {$rmed > 0 && $rmax > 3 * $rmed} {
          puts ""
          puts "  *** OUTLIER: max RTT ($rmax) is more than 3x the median ($rmed)."
          puts "      The mean above is not trustworthy. Run epd_raw to see which"
          puts "      sample it was and what its raw counters look like."
     }

     # Where on the counter the run happened. Useful for two things: seeing
     # that the run really spanned a wrap (or did not), and sanity-checking
     # the elapsed wall time against the JTAG cost from epd_calibrate.
     set first [lindex $raw_t1p 0]
     set last  [lindex $raw_t2 end]
     puts [format "raw span: t1'(first)=%u  t2(last)=%u  elapsed=%d cycles (%.1f ms)" \
               $first $last [_epd_sub32 $last $first] \
               [expr {[_epd_sub32 $last $first] * $::EPD_CLK_NS / 1000000.0}]]
     puts "For per-sample raw counters use: epd_raw $count"
}

# =============================================================================
# hls_recv_krnl -- КОНТРОЛЬНЫЙ ОПЫТ, апстримное ядро без единой нашей строки
# =============================================================================
#
# ЗАЧЕМ ОНО ЗДЕСЬ. Три битстрима подряд дают одно: enable читается обратно,
# listenAttempts=0, portState=0. По сгенерированному RTL исключены все пять
# известных дефектов HLS, неверный адрес, чужой битстрим и сброс; стек при этом
# ЖИВОЙ -- пинги идут, ARP отвечает. То есть отладка упёрлась в вопрос, который
# нельзя решить чтением кода: виноваты наши ядра или связка BD+JTAG?
#
# hls_recv_krnl отвечает на него, потому что он:
#   * АПСТРИМНЫЙ -- создан zhe в 2020, последняя правка 2022, нами не тронут;
#   * ОТКРЫВАЕТ LISTEN -- ровно тот путь, который у нас не работает;
#   * СЫРОЕ HLS БЕЗ ОБЁРТКИ -- проверяет BD и JTAG в чистом виде;
#   * использует ШТАТНУЮ схему s_axilite + ap_ctrl_hs, от которой мы отказались
#     в пользу ap_ctrl_none + регистры в HDL-обёртке.
#
# Исход читается однозначно:
#   соединение установилось -> штатная схема и JTAG исправны, виновата НАША;
#   не установилось         -> проблема в BD/JTAG, наши ядра ни при чём.
#
# ПРО JTAG ВМЕСТО XRT. Ядро писалось под XRT+XDMA, но это неважно: jtag_axi --
# обычный AXI-Lite мастер, и для s_axilite-ядра источник транзакций неотличим.
# Доказательство прямо в этой же сборке: network_krnl -- тоже апстримное ядро с
# s_axilite и ap_ctrl_hs под XRT, и по JTAG оно работает (пинги идут). XRT
# добавлял только выделение буферов в DDR (мы делаем это руками через
# network_set_buffers) и ожидание прерываний (мы опрашиваем регистр).
#
# ЗАПУСК ЧЕРЕЗ ap_start, А НЕ ЧЕРЕЗ enable -- и это, возможно, суть различия.
# Здесь хост пишет параметры и дёргает ap_start; у наших ядер ap_start в обёртке
# нужен «для вида», а работу разрешает отдельный регистр enable. Если у recv
# заработает, версия «дело в отказе от ap_start как пускового механизма» станет
# правдоподобной.
#
# СМЕЩЕНИЯ -- из сгенерированного xhls_recv_krnl_hw.h (печатается в конце
# export_hls_ip.tcl), не угаданы:
set ::RECV_OFF_AP_CTRL   0x00
set ::RECV_OFF_USECONN   0x10
set ::RECV_OFF_BASEPORT  0x18
set ::RECV_OFF_RXBYTES   0x20

# Настройка + запуск. useConn портов начиная с basePort.
#
# expectedRxByteCnt -- сколько байт ядро ждёт на сессию; для проверки listen
# значение неважно, берём заведомо большое, чтобы ядро не завершилось раньше,
# чем мы успеем подключиться.
proc recv_start {{basePort 5001} {useConn 1} {rxBytes 1000000} {n 1}} {
     set base [ouch_base_user $n]

     axi_write32 [expr {$base + $::RECV_OFF_USECONN}]  $useConn
     axi_write32 [expr {$base + $::RECV_OFF_BASEPORT}] $basePort
     axi_write32 [expr {$base + $::RECV_OFF_RXBYTES}]  $rxBytes

     # Читаем обратно ДО запуска: если параметры не доехали, ap_start бессмысленен.
     set rd_conn [axi_read32 [expr {$base + $::RECV_OFF_USECONN}]]
     set rd_port [axi_read32 [expr {$base + $::RECV_OFF_BASEPORT}]]
     puts "recv\[$n\]: useConn=$rd_conn basePort=$rd_port rxBytes=$rxBytes"
     if {$rd_conn != $useConn || $rd_port != $basePort} {
          puts "  *** WRITE NOT CONFIRMED -- проверь ouch_base_user $n и битстрим"
          return 0
     }
     puts "  write confirmed"

     # ap_start + auto_restart, как в network_start: ядро должно работать
     # непрерывно, а не отработать один раз и остановиться.
     axi_write32 [expr {$base + $::RECV_OFF_AP_CTRL}] 0x81
     recv_status $n
     return 1
}

# ap_ctrl глазами хоста. ap_done очищается ЧТЕНИЕМ (Read/COR), поэтому два
# чтения подряд дадут разное -- это нормально, не признак поломки.
proc recv_status {{n 1}} {
     set ctrl [axi_read32 [expr {[ouch_base_user $n] + $::RECV_OFF_AP_CTRL}]]
     puts [format "recv\[%d\]: ap_ctrl=0x%02x (ap_start=%d ap_done=%d ap_idle=%d auto_restart=%d)" \
               $n $ctrl [expr {$ctrl & 1}] [expr {($ctrl >> 1) & 1}] \
               [expr {($ctrl >> 2) & 1}] [expr {($ctrl >> 7) & 1}]]
     if {($ctrl & 1) == 0} {
          puts "  -> ap_start снят: ядро завершилось и не перезапустилось."
          puts "     Для контрольного опыта это уже ответ: значит ap_ctrl_hs"
          puts "     отрабатывает, но auto_restart не удержал ядро запущенным."
     }
     return $ctrl
}

# Полный контрольный опыт одной командой.
#
# ПОСЛЕ НЕЁ -- подключиться с PC: ncat <ip> <basePort>. Установившееся
# соединение означает, что listen-порт реально открыт в стеке.
proc recv_bringup {ip_str mac_str {basePort 5001} {n 1}} {
     echo_bringup $ip_str $mac_str $n
     puts ""
     recv_start $basePort 1 1000000 $n
     puts ""
     puts "Теперь с PC:  ncat [_de_dotted $ip_str] $basePort"
     puts "  соединение установилось -> listen РАБОТАЕТ (штатная схема исправна)"
     puts "  отказ в соединении      -> listen не открылся"
     puts ""
     puts "Если ncat недоступен:  telnet [_de_dotted $ip_str] $basePort"
}

# =============================================================================
# vio_dump -- TCP stack counters from the VIO
# =============================================================================
#
# Diagnostics: run it when something does not work. Not needed on a normal run.
#
# The probes are vio_network from network_krnl/src/hdl/network_stack.sv (the
# probe_in0..18 order is defined there). NOT to be confused with
# stat_rx_aligned: that signal is not wired to a VIO at all, it is on an ILA
# in cmac_krnl (inst_ila_0, probe0), and an ILA is read by arming a trigger,
# not by reading a value.
#
# refresh_hw_vio IS REQUIRED: without it Vivado returns the values sampled
# when the bitstream was loaded, i.e. zeros. That looks like "the stack is
# dead".
set ::VIO_PROBE_NAMES {
     ip_toe ip_iph mac_mie mac_arp ip_arp
     rx_words rx_pkts tx_words tx_pkts
     tcp_rx tcp_tx arp_rx arp_tx udp_rx udp_tx
     icmp_rx icmp_tx stream_down mac_addr
}

# Finding the probes of one VIO is fiddly: -of_objects (plural) returns
# nothing for hw_vio objects in some Vivado versions -- which is exactly the
# "No matching hw_probes were found" warning. Try the documented spellings in
# order and use whichever answers.
proc _vio_probes {vio} {
     # 1) singular -of_object, the form the VIO docs use
     set ps [get_hw_probes -quiet -of_object $vio]
     if {[llength $ps] > 0} { return $ps }

     # 2) plural, works on some versions
     set ps [get_hw_probes -quiet -of_objects $vio]
     if {[llength $ps] > 0} { return $ps }

     # 3) fall back to matching by name: probe names are prefixed with the
     #    VIO's own path, e.g. ".../vio_network/probe_in0".
     set ps [get_hw_probes -quiet "[get_property NAME $vio]/*"]
     if {[llength $ps] > 0} { return $ps }

     # 4) last resort: every probe in the device, filtered by the VIO path.
     set out {}
     set vname [get_property NAME $vio]
     foreach p [get_hw_probes -quiet *] {
          if {[string match "$vname*" [get_property NAME $p]]} { lappend out $p }
     }
     return $out
}

proc vio_dump {} {
     set vios [get_hw_vios]
     if {[llength $vios] == 0} {
          puts "vio_dump: no VIOs found -- is the right bitstream loaded?"
          return
     }
     refresh_hw_vio $vios

     foreach vio $vios {
          puts "--- [get_property NAME $vio] ---"
          set ps [_vio_probes $vio]
          if {[llength $ps] == 0} {
               puts "  (no probes found for this VIO)"
               puts "  Try it by hand to see what the names look like:"
               puts "    get_hw_probes -of_object \[lindex \[get_hw_vios\] 0\]"
               puts "    get_hw_probes *"
               continue
          }
          foreach p $ps {
               set short [get_property NAME.SHORT $p]
               # probe_inN -> a meaningful name from the table above.
               set nm $short
               if {[regexp {probe_in(\d+)$} $short -> i]} {
                    set alias [lindex $::VIO_PROBE_NAMES $i]
                    if {$alias ne ""} { set nm [format "%-11s (%s)" $alias $short] }
               }
               puts [format "  %-28s %s" $nm [get_property INPUT_VALUE $p]]
          }
     }
}

# =============================================================================
# hls_dual_echo_krnl -- dual-QSFP echo, per-half listen port from the host
# =============================================================================
#
# Bringup order (the order matters, see below):
#     echo_bringup_dual 0a01d498 000a35029de5 0a01d499 000a35029de6
#     dual_echo_configure 7001 7002
#     if {![dual_echo_start]} { return 0 }
#     dual_echo_status              ; # did the listen ports actually open?
#
# Or all of it in one call, arguments grouped per interface (ip mac port):
#     dual_echo_bringup 0a01d498 000a35029de5 7001 \
#                       0a01d499 000a35029de6 7002
#
# Each half gets its OWN listen port: portA -> half a (QSFP0, network_krnl_1),
# portB -> half b (QSFP1, network_krnl_2). The same number on both is legal
# (separate stacks, separate port tables), but different numbers make a failed
# connect diagnostic: you learn which half is at fault instead of suspecting
# both the IP and the port.
#
# WHY enable LAST. The kernel is ap_ctrl_none, so it starts running the
# moment reset is released -- long before JTAG shows up. Until enable is
# written it does not touch a single stack port, because (a) the listen ports
# may not be written yet, and (b) network_krnl may not be started yet, and the
# TOE only latches its IP on the ap_start edge (network_stack.sv:946) while
# being reset only by net_aresetn (network_stack.sv:656). Requesting a
# listen port before the stack is up is exactly the race that leaves the
# port half-open with no way to tell from outside.
#
# ADDRESS MAP -- see the Russian note below for where it comes from and why it
# changed completely. Summary:
#
#   0x00  ap_ctrl        bit0=ap_start bit1=ap_done bit2=ap_idle bit7=auto_restart
#   0x10  listenPortA    RW
#   0x18  listenPortB    RW
#   0x20  listenAtt_a    RO
#   0x30  portState_a    RO   0=not requested 1=requested 2=OPEN
#   0x40  notify_a       RO
#   0x50  listenAtt_b    RO
#   0x60  portState_b    RO
#   0x70  notify_b       RO
#
# There is no enable register any more: ap_start took over that role. The kernel
# stays in ap_idle until ap_start is written, so it cannot touch the stack before
# network_start -- which is exactly what enable was invented for.
# Смещения ВЗЯТЫ ИЗ СГЕНЕРИРОВАННОГО xhls_dual_echo_krnl_hw.h, а не подобраны.
#
# Путь к файлу печатает шаг user_ip; полностью он такой:
#   src/hls/hls_dual_echo_krnl_ip_proj/sol1/impl/ip/drivers/
#       hls_dual_echo_krnl_v1_0/src/xhls_dual_echo_krnl_hw.h
#
# ЭТО НЕ КОСМЕТИКА. Пока ядро было ap_ctrl_none с рукописной HDL-обёрткой,
# *_hw.h не генерировался вообще, и смещения жили только здесь -- их не сверяло
# НИЧТО. После перехода на s_axilite карта изменилась ЦЕЛИКОМ, ни одно значение не
# совпало со старым:
#
#     listenPortA      0x18 -> 0x10        listenAttempts_b 0x40 -> 0x50
#     listenPortB      0x20 -> 0x18        portState_b      0x44 -> 0x60
#     listenAttempts_a 0x30 -> 0x20        notifyCount_b    0x48 -> 0x70
#     portState_a      0x34 -> 0x30
#     notifyCount_a    0x38 -> 0x40
#
# Причём по старому 0x10 лежал enable, а теперь там listenPortA: со старой картой
# порт уходил бы в чужой регистр, а телеметрия читалась бы из пустоты -- ровно тот
# класс отказа, который мы неделю искали в логике ядра.
#
# ПОСЛЕ ЛЮБОЙ ПРАВКИ СОСТАВА АРГУМЕНТОВ .cpp СВЕРИТЬ ЗАНОВО: HLS раскладывает
# регистры по своему порядку, добавление одного скаляра сдвигает всё ниже него.
set ::DE_OFF_AP_CTRL         0x00
set ::DE_OFF_LISTEN_PORT_A   0x10
set ::DE_OFF_LISTEN_PORT_B   0x18
set ::DE_OFF_LISTEN_ATT_A    0x20
set ::DE_OFF_PORT_STATE_A    0x30
set ::DE_OFF_NOTIFY_A        0x40
set ::DE_OFF_LISTEN_ATT_B    0x50
set ::DE_OFF_PORT_STATE_B    0x60
set ::DE_OFF_NOTIFY_B        0x70

# Write the listen ports -- one per half. portB defaults to portA when
# omitted, which keeps the old single-port behaviour available.
#
# The same number on both halves is legal: the halves sit on different
# network_krnl instances, each with its own listeningPortTable. Different
# numbers are still preferable for debugging -- a failed connect then tells
# you WHICH half is at fault instead of leaving IP and port both suspect.
proc dual_echo_configure {listenPortA {listenPortB ""} {n 1}} {
     set base [ouch_base_user $n]
     if {$listenPortB eq ""} { set listenPortB $listenPortA }

     puts "dual_echo\[$n\]: listenPortA=$listenPortA listenPortB=$listenPortB"
     axi_write32 [expr {$base + $::DE_OFF_LISTEN_PORT_A}] $listenPortA
     axi_write32 [expr {$base + $::DE_OFF_LISTEN_PORT_B}] $listenPortB

     # Verify by reading back: without this, "the kernel does not respond"
     # is indistinguishable from "the offsets are wrong".
     set rd_a [axi_read32 [expr {$base + $::DE_OFF_LISTEN_PORT_A}]]
     set rd_b [axi_read32 [expr {$base + $::DE_OFF_LISTEN_PORT_B}]]
     if {$rd_a != $listenPortA || $rd_b != $listenPortB} {
          puts "  *** WRITE NOT CONFIRMED (read A=$rd_a B=$rd_b,"
          puts "      expected A=$listenPortA B=$listenPortB)"
          puts "      Either this bitstream has no s_axi_control on the kernel,"
          puts "      or DE_OFF_* offsets do not match xhls_dual_echo_krnl_hw.h."
          return 0
     }
     puts "  write confirmed"
     return 1
}

# Start the kernel. LAST, after dual_echo_configure and echo_bringup_dual.
#
# WHAT STARTS THE WORK: ap_start (bit 0 of ap_ctrl at 0x00), nothing else.
#
# The kernel is s_axilite + ap_ctrl_hs, exactly like hls_recv_krnl and
# network_krnl. Writing 0x81 sets ap_start together with auto_restart (bit 7), so
# the hardware relaunches the region by itself and the kernel runs continuously --
# no host involvement per pass.
#
# THIS ALSO CLOSES THE RACE WITH THE STACK, which is why the enable register is
# gone. The kernel sits in ap_idle until ap_start is written, so it physically
# cannot request a listen port before network_start has given TOE its IP. enable
# existed only to hold the kernel back; ap_start does that by construction.
#
# HISTORY, so nobody reintroduces the old scheme. The kernel used to be
# ap_ctrl_none with the control registers in a hand-written HDL wrapper, because
# UG1393 forbids s_axilite on a free-running kernel. That cost a week:
#
#   * ap_sync_done -- the AND over ap_done of all 14 dataflow stages -- froze the
#     region after a single pass, so listenAttempts stayed 0 while the registers
#     read back fine;
#   * output scalars do not work without ap_done, so telemetry was always zero;
#   * the address map was hand-maintained and verified by nothing.
#
# All three vanish with ap_ctrl_hs: auto_restart provides continuity,
# ap_done provides telemetry, and xhls_dual_echo_krnl_hw.h provides the map.
# Verified by simulation before any board time (tb_core_ap_done, ALL GREEN):
# 10 listen retries per 3M cycles, portState=1, listenAttempts matching the bus,
# both halves identical.
proc dual_echo_start {{n 1}} {
     set base [ouch_base_user $n]
     set addr [expr {$base + $::DE_OFF_AP_CTRL}]

     # ap_start=1 + auto_restart=1. Same value network_krnl is started with.
     axi_write32 $addr 0x81

     set ctrl [axi_read32 $addr]
     puts [format "dual_echo\[$n\]: ap_ctrl=0x%02x (ap_start=%d ap_done=%d ap_idle=%d)" \
               $ctrl [expr {$ctrl & 1}] [expr {($ctrl >> 1) & 1}] [expr {($ctrl >> 2) & 1}]]

     # ap_idle must drop: it is the one bit that says the region actually started.
     # A kernel that stays idle means ap_start never took -- wrong address, or no
     # s_axi_control in this bitstream.
     if {($ctrl >> 2) & 1} {
          puts "  *** STILL IDLE -- ap_start did not take."
          puts "      Check that DE_OFF_* match xhls_dual_echo_krnl_hw.h and that"
          puts "      this bitstream has s_axi_control on the kernel."
          return 0
     }
     return 1
}

proc dual_echo_stop {{n 1}} {
     set base [ouch_base_user $n]
     axi_write32 [expr {$base + $::DE_OFF_AP_CTRL}] 0x00
     puts "dual_echo\[$n\]: auto_restart cleared -- stops after the current pass"
     return 1
}

# Telemetry. This is what tells "the port never opened" apart from "the port
# is open but nobody connected" -- the distinction we could not make before.
proc dual_echo_status {{n 1}} {
     set base [ouch_base_user $n]

     set att_a [axi_read32 [expr {$base + $::DE_OFF_LISTEN_ATT_A}]]
     set st_a  [axi_read32 [expr {$base + $::DE_OFF_PORT_STATE_A}]]
     set nt_a  [axi_read32 [expr {$base + $::DE_OFF_NOTIFY_A}]]
     set att_b [axi_read32 [expr {$base + $::DE_OFF_LISTEN_ATT_B}]]
     set st_b  [axi_read32 [expr {$base + $::DE_OFF_PORT_STATE_B}]]
     set nt_b  [axi_read32 [expr {$base + $::DE_OFF_NOTIFY_B}]]

     puts "dual_echo half a: listenAttempts=$att_a state=[_de_state $st_a] notifications=$nt_a"
     puts "dual_echo half b: listenAttempts=$att_b state=[_de_state $st_b] notifications=$nt_b"

     foreach {nm st att} [list a $st_a $att_a b $st_b $att_b] {
          if {$st == 0} {
               puts "  half $nm -> never requested a port: was dual_echo_start called?"
          } elseif {$st == 1 && $att > 3} {
               puts "  half $nm -> the stack is not answering the listen request."
               puts "     listenAttempts keeps growing, so the kernel retries but"
               puts "     gets no port_status. Check that echo_bringup_dual ran"
               puts "     BEFORE dual_echo_start, and run vio_dump."
          }
     }
     return [list $att_a $st_a $nt_a $att_b $st_b $nt_b]
}

proc _de_state {v} {
     switch -- $v {
          0 { return "0(not-requested)" }
          1 { return "1(requested)" }
          2 { return "2(OPEN)" }
          default { return "$v(?)" }
     }
}

# Bringup everything in the right order, one call.
#
# Arguments are grouped PER INTERFACE -- ip mac port, then ip mac port again,
# so each triple reads as the config of one device:
#
#   dual_echo_bringup 0a01d498 000a35029de5 7001 \
#                     0a01d499 000a35029de6 7002
#
# First triple is QSFP0 (half a, network_krnl_1), second is QSFP1 (half b,
# network_krnl_2). The two ports may be equal -- separate stacks, separate
# port tables -- but different numbers make a failed connect tell you which
# half is at fault.
proc dual_echo_bringup {ip_str1 mac_str1 port1 ip_str2 mac_str2 port2} {
     echo_bringup_dual $ip_str1 $mac_str1 $ip_str2 $mac_str2
     puts ""
     if {![dual_echo_configure $port1 $port2]} { return 0 }
     if {![dual_echo_start]} { return 0 }
     puts ""
     dual_echo_status
     puts ""
     puts "Now from the PC (note the port that goes with each IP):"
     puts "  ncat [_de_dotted $ip_str1] $port1"
     puts "  ncat [_de_dotted $ip_str2] $port2"
     return 1
}

# 0a01d498 -> 10.1.212.152. Only for printing the hint above: retyping the
# hex by hand is exactly where a wrong-IP test comes from.
proc _de_dotted {ip_str} {
     set ip [_hex2int $ip_str]
     return [format "%d.%d.%d.%d" \
                 [expr {($ip >> 24) & 0xff}] [expr {($ip >> 16) & 0xff}] \
                 [expr {($ip >> 8) & 0xff}]  [expr {$ip & 0xff}]]
}
